name: "QMK firmware"

on:
  workflow_dispatch:

jobs:
  qmk-compile:
    name: Compile firmware
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get install git python3-pip

      - name: Install QMK
        run: python3 -m pip install --user qmk

      - name: Setup
        run: qmk setup --yes

      - name: Compile
        run: qmk compile -kb massdrop/ctrl -km default

      - name: Copy
        run: mkdir ~/build/ && cp ~/qmk_firmware/massdrop_ctrl_default.bin ~/build/

      - name: Deploy to build branch
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: build
          FOLDER: ~/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}